// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anewyrytsnadvmysxzek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZXd5cnl0c25hZHZteXN4emVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDU2MzUsImV4cCI6MjA2MDcyMTYzNX0.G4uyLchLn9B3U21OKAuuzcfxYUXqvu-7NXl5C1rrpVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);