// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jygnglzdxicwgnyczqfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5Z25nbHpkeGljd2dueWN6cWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDM5MjgsImV4cCI6MjA2ODA3OTkyOH0.e3bpWNkBVD5i-Tr2gGfeimpboDkQpEE0FH9XwBQU1cU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});